In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size = 1000

In [8]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[714, 269, 390, 19],
 [714, 269, 390, 458],
 [714, 522, 390, 83],
 [455, 946, 731, 166, 914],
 [455, 946, 731, 166, 525],
 [715, 714, 692, 390, 306],
 [82, 30, 952, 166]]

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import  Sequential

In [ ]:
import numpy as np

In [13]:
sent_length=8

In [15]:
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[  0   0   0   0 714 269 390  19]
 [  0   0   0   0 714 269 390 458]
 [  0   0   0   0 714 522 390  83]
 [  0   0   0 455 946 731 166 914]
 [  0   0   0 455 946 731 166 525]
 [  0   0   0 715 714 692 390 306]
 [  0   0   0   0  82  30 952 166]]


In [18]:
#feature Representation
dim =10

In [19]:
model= Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length ))
model.compile('adam', 'mse')

c:\Users\Lenovo\OneDrive\Desktop\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[[ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00029502, -0.03243097, -0.04163488, -0.02174375,
         -0.01472676, -0.0189732 ,  0.00752145,  0.01081987,
          0.0029695 , -0.04827681],
        [-0.01858705,  0.00449382, -0.01309507, -0.0379198 ,
         -0.02712859,  0.03044684, -0.02143637,  0.01448053,
         -0.00223049,  0.04958134],
        [ 0.04229024, -0.0020857 , -0.03705671,  0.0

In [26]:
embedded_docs[0]

array([  0,   0,   0,   0, 714, 269, 390,  19], dtype=int32)

In [31]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([[[ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00113788,  0.03475587,  0.03566172, -0.00451636,
          0.03200079,  0.04822889,  0.02052094,  0.00090989,
         -0.0441399 , -0.04611091],
        [ 0.00029502, -0.03243097, -0.04163488, -0.02174375,
         -0.01472676, -0.0189732 ,  0.00752145,  0.01081987,
          0.0029695 , -0.04827681],
        [-0.01858705,  0.00449382, -0.01309507, -0.0379198 ,
         -0.02712859,  0.03044684, -0.02143637,  0.01448053,
         -0.00223049,  0.04958134],
        [ 0.04229024, -0.0020857 , -0.03705671,  0.0